version: "3.9"
services:
    php_server:
        build:
            dockerfile: ./docker/Dockerfile
            context: .
        ports:
            - "80:80"
        volumes:
            - .:/var/www
        networks:
            - network
    mysql_database:
        image: mysql
        restart: always
        ports:
            - "3306:3306"
        env_file:
            - .env
        networks:
            - network
networks:
    network:
        driver: bridge